runtime: java
env: flex
runtime_config:
    operating_system: ubuntu18
    runtime_version: 11
handlers:
- url: /.*
script: this field is requerid, but ignored

env_variables:
    bucket_name: bucketcloudortizz